name: asset_delivery_example
description: "Demonstrates how to use the asset_delivery plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.2
  
dependencies:
  flutter:
    sdk: flutter

  asset_delivery:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
